### ISSUE TITLE
Move to junkyard

### ISSUE THREAD

**Issue by arj03** [ssbc/ssb-contacts#3]
@mixmix I think this needs to be moved to the ssb-junkyard, can you move it or give me access to the organization so I can move it myself? :) Thanks

**Comment by dominictarr** [comment]
@arj03 added you to the ssb-junkyard org

**Comment by arj03** [comment]
Thank you

**Comment by mixmix** [comment]
sorry @arj03 I don't check my email really so mentioning me on github doesn't work. I don't have a good system at all.
Please feel free to DM me on scuttlebutt or signal anytime, I will respond very promptly on those fronts
